-- Histórico de Banco de Dados (Supabase) - CaloriesBot

create table logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  food text not null,
  weight text,
  kcal integer not null,
  user_id text not null,
  user_name text
);

-- Tabela de perfis de usuário
create table profiles (
  user_id text primary key,
  weight float8 not null,
  height float8 not null,
  age integer not null,
  gender text not null, -- 'M' ou 'F'
  tdee float8 not null, -- Gasto Calórico Diário
  created_at timestamptz default now()
);

-- 1. Atualiza a tabela 'logs' com o que está faltando
ALTER TABLE logs 
  ADD COLUMN IF NOT EXISTS protein INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carbs INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fat INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS meal_type TEXT DEFAULT 'Outro';

-- 2. Atualiza a tabela 'profiles' com o que está faltando
ALTER TABLE profiles 
  ADD COLUMN IF NOT EXISTS activity TEXT,
  ADD COLUMN IF NOT EXISTS goal TEXT DEFAULT 'manter';

DO $$ 
BEGIN 
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='logs' AND column_name='is_precise'
  ) THEN
    ALTER TABLE logs ADD COLUMN is_precise BOOLEAN DEFAULT FALSE;
  END IF;
END $$;

-- 1. Habilitar pgvector
create extension if not exists vector;

-- 2. Adicionar coluna de embedding (se não existir)
-- Nota: Você pode precisar adicionar isso a uma tabela de cache ou logs
alter table logs add column if not exists f_embedding vector(768);

-- 3. Criar função de busca
create or replace function match_logs (
  query_embedding vector(768),
  match_threshold float,
  match_count int,
  p_user_id text
)
returns table (
  id bigint,
  food text,
  weight text,
  kcal int,
  protein int,
  carbs int,
  fat int,
  meal_type text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    logs.id,
    logs.food,
    logs.weight,
    logs.kcal,
    logs.protein,
    logs.carbs,
    logs.fat,
    logs.meal_type,
    1 - (logs.f_embedding <=> query_embedding) as similarity
  from logs
  where logs.user_id = p_user_id
    and 1 - (logs.f_embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
end;
$$;

alter table logs add column confirmations int default 0;

-- 1. Habilita o suporte a vetores
create extension if not exists vector;

-- 2. Adiciona a coluna de inteligência aos logs
alter table logs add column if not exists embedding vector(768);

-- 3. Cria o índice para buscas ultra-rápidas
create index on logs using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- Nova Tabela: FSM do Telegram (Estado e Dados do Bot)
CREATE TABLE fsm_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    bot_id BIGINT,
    chat_id BIGINT,
    user_id BIGINT,
    destiny TEXT,
    state TEXT,
    data JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(bot_id, chat_id, user_id, destiny)
);
